### ISSUE TITLE
Investigate wider content area for lab instructions

### ISSUE THREAD

**Issue by sfeeser** [alta3/mdBook#5]
The red arrows below illustrate wasted screen real estate that could be used to display content. Ideally, content would extend (green arrow) into that area rather than wrapping.

![image](https://user-images.githubusercontent.com/13711668/84657461-50395d00-aee2-11ea-8a16-b45f800c23e6.png)

**Comment by bryfry** [comment]
Updating and maintaining mdbook css changes is more work than this improvement provides value.

Closing due to lack of will / time.  Might re-open some day when we're looking for work.
